# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ${{ if eq( variables['Build.SourceBranchName'], 'master' ) }}:
    tag_branch_name: '$(Build.SourceBranchName'
  ${{ if ne( variables['System.PullRequest.SourceBranch'], variables['noSuch']) }}:
    tag_branch_name: ${{ variables['System.PullRequest.SourceBranch'] }}

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'registry.k8s-test.vcp.sh'
        repository: 'nordlager-backend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          ${{ if ne( variables['tag_branch_name'], variables['noSuch']) }}
            $(tag_branch_name)

